//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSem3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class employee
    {
        public int employee_id { get; set; }
        [DisplayName("Employee Name")]
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Employee Name is not empty???!")]
        public string employee_name { get; set; }
        [DisplayName("Address")]
        [DataType(DataType.MultilineText)]
        [Required(ErrorMessage = "Employee Name is not empty???!")]
        public string address { get; set; }
        [DisplayName("Phone")]
        [DataType(DataType.PhoneNumber)]
        [Required(ErrorMessage = "Address is not empty???!")]
        public string phone { get; set; }
        [DisplayName("Email")]
        [DataType(DataType.EmailAddress,ErrorMessage ="Email is not valid")]
        [Required(ErrorMessage = "Email is not empty???!")]
        public string email { get; set; }
        [DisplayName("ID Job")]
        [Required]

        public Nullable<int> job_title_id { get; set; }
        [DisplayName("ID Department")]
        [Required]
        public Nullable<int> department_id { get; set; }
        [DisplayName("Username")]
        [Required(ErrorMessage = "Username is not empty???!")]

        public string username { get; set; }
        [Required(ErrorMessage ="Password is not empty???!")]
        [DisplayName("Password")]
        [DataType(DataType.Password)]
        public string password { get; set; }
    
        public virtual department department { get; set; }
        public virtual job_title job_title { get; set; }
    }
}
