//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSem3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class favorite_service
    {
        public int favorite_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<int> service_id { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual service service { get; set; }
    }
}
