//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSem3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Sem3Entities1 : DbContext
    {
        public Sem3Entities1()
            : base("name=Sem3Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<favorite_service> favorite_service { get; set; }
        public virtual DbSet<fee> fees { get; set; }
        public virtual DbSet<job_title> job_title { get; set; }
        public virtual DbSet<payment> payments { get; set; }
        public virtual DbSet<product_service> product_service { get; set; }
        public virtual DbSet<service> services { get; set; }
    }
}
