//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSem3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_service
    {
        public int product_service_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public string product_service_name { get; set; }
        public string description { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
